// #include "absvdi3.c"
// #include "absvsi2.c"
// #include "absvti2.c"
// #include "adddf3.c"
// #include "addsf3.c"
// #include "addtf3.c"
// #include "addvdi3.c"
// #include "addvsi3.c"
// #include "addvti3.c"
// #include "apple_versioning.c"
// #include "ashldi3.c"
// #include "ashlti3.c"
// #include "ashrdi3.c"
// #include "ashrti3.c"
// #include "clear_cache.c"
// #include "clzdi2.c"
// #include "clzsi2.c"
// #include "clzti2.c"
// #include "cmpdi2.c"
// #include "cmpti2.c"
// #include "compared$f2.c"
// #include "comparesf2.c"
// #include "cpu_model.c"
// #include "ctzdi2.c"
// #include "ctzsi2.c"
// #include "ctzti2.c"
#include "divdc3.c"
#include "divdf3.c"
#include "divdi3.c"
#include "divmoddi4.c"
#include "divmodsi4.c"
#include "divsc3.c"
#include "divsf3.c"
#include "divsi3.c"
#include "divtc3.c"
#include "divti3.c"
#include "divtf3.c"
#include "divxc3.c"
// #include "extendsfdf2.c"
// #include "extendhfsf2.c"
// #include "ffsdi2.c"
// #include "ffsti2.c"
// #include "fixdfdi.c"
// #include "fixdfsi.c"
// #include "fixdfti.c"
// #include "fixsfdi.c"
// #include "fixsfsi.c"
// #include "fixsfti.c"
// #include "fixunsdfdi.c"
// #include "fixunsdfsi.c"
// #include "fixunsdfti.c"
// #include "fixunssfdi.c"
// #include "fixunssfsi.c"
// #include "fixunssfti.c"
// #include "fixunsxfdi.c"
// #include "fixunsxfsi.c"
// #include "fixunsxfti.c"
// #include "fixxfdi.c"
// #include "fixxfti.c"
// #include "floatdidf.c"
// #include "floatdisf.c"
// #include "floatdixf.c"
// #include "floatsidf.c"
// #include "floatsisf.c"
// #include "floattidf.c"
// #include "floattisf.c"
// #include "floattixf.c"
// #include "floatundidf.c"
// #include "floatundisf.c"
// #include "floatundixf.c"
// #include "floatunsidf.c"
// #include "floatunsisf.c"
// #include "floatuntidf.c"
// #include "floatuntisf.c"
// #include "floatuntixf.c"
// #include "int_util.c"
// #include "lshrdi3.c"
// #include "lshrti3.c"
#include "moddi3.c"
#include "modsi3.c"
#include "modti3.c"
#include "muldc3.c"
#include "muldf3.c"
#include "muldi3.c"
#include "mulodi4.c"
#include "mulosi4.c"
#include "muloti4.c"
#include "mulsc3.c"
// #include "mulsf3.c"
#include "multi3.c"
#include "multf3.c"
#include "mulvdi3.c"
#include "mulvsi3.c"
#include "mulvti3.c"
#include "mulxc3.c"
#include "negdf2.c"
#include "negdi2.c"
#include "negsf2.c"
#include "negti2.c"
#include "negvdi2.c"
#include "negvsi2.c"
#include "negvti2.c"
#include "paritydi2.c"
#include "paritysi2.c"
#include "parityti2.c"
// #include "popcountdi2.c"
// #include "popcountsi2.c"
// #include "popcountti2.c"
#include "powidf2.c"
#include "powisf2.c"
#include "powitf2.c"
#include "powixf2.c"
#include "subdf3.c"
#include "subsf3.c"
#include "subvdi3.c"
#include "subvsi3.c"
#include "subvti3.c"
#include "subtf3.c"
// #include "trampoline_setup.c"
// #include "truncdfhf2.c"
// #include "truncdfsf2.c"
// #include "truncsfhf2.c"
#include "ucmpdi2.c"
#include "ucmpti2.c"
#include "udivdi3.c"
#include "udivmoddi4.c"
#include "udivmodsi4.c"
#include "udivmodti4.c"
#include "udivsi3.c"
#include "udivti3.c"
#include "umoddi3.c"
#include "umodsi3.c"
#include "umodti3.c"
